#!/usr/bin/env python3
"""Generate render.yaml from the single BLOGS source of truth, with per-blog build
filters so editing one blog only rebuilds that one Render service.

Run from repo root:  python3 scripts/gen_render_yaml.py
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generate_sites import BLOGS

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO_URL = "https://github.com/vantatechca/crosta-blogs.git"   # <-- set per client
HUGO_VERSION = "0.139.0"

def service_name(slug, title):
    return title.lower().replace("&", "and").replace("'", "").replace(" ", "-")

header = (
    "# Render Blueprint — GENERATED by scripts/gen_render_yaml.py. Do not hand-edit;\n"
    "# change the BLOGS list in scripts/generate_sites.py and re-run the generator.\n"
    "#\n"
    "# One free Static Site per blog. After the blueprint applies, set per-service\n"
    "# Build Filters in the Render dashboard (Settings -> Build Filters) so a push that\n"
    "# only touches one blog rebuilds only that service. (Build filters are a dashboard\n"
    "# setting, not a blueprint field.)\n"
    "# After first deploy: attach each real domain in the dashboard (free SSL).\n\n"
    "services:\n"
)

blocks = []
for slug, title, theme, domain, tagline in BLOGS:
    name = service_name(slug, title)
    blocks.append(f"""  - type: web
    runtime: static
    name: {name}
    repo: {REPO_URL}
    branch: main
    buildCommand: ./render-build.sh {slug}
    staticPublishPath: ./public/{slug}
    envVars:
      - key: HUGO_VERSION
        value: "{HUGO_VERSION}"
""")

(ROOT / "render.yaml").write_text(header + "\n".join(blocks))
print(f"Wrote render.yaml with {len(BLOGS)} services.")
